vim.keymap.set("n", "<leader>pv", vim.cmd.Ex)
vim.keymap.set("n", "<leader>a", vim.lsp.handlers["textDocument/codeAction"])
vim.keymap.set("n", "<leader>d", vim.lsp.handlers["textDocument/definition"])
vim.keymap.set("n", "<leader>r", function()
    return ":IncRename " .. vim.fn.expand("<cword>")
end, { expr = true })
